# .goreleaser.yml
# Build customization
builds:
  - env:
    - GO111MODULE=on
  - binary: shino
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
# Archive customization
archive:
  format: tar.gz